#!/usr/bin/env python3
"""Synchronize the runtime schema mirrors touched by revision 4 (no Go behavior)."""
import argparse
import json
from pathlib import Path
import re
import model

ROOT=Path(__file__).resolve().parents[2]
D=json.loads((ROOT/'docs/implementation/adapter-schemas.json').read_text())['definitions']
OPS={o['id']:o for o in model.OPS}
def compact(x):return json.dumps(x,separators=(',',':'),ensure_ascii=False)
def closure(names,defs):
 out={}
 def visit(name):
  if name in out:return
  out[name]=defs[name]
  for ref in re.findall(r'"\$ref":\s*"#\/\$defs\/([^"/]+)"',json.dumps(defs[name])):visit(ref)
 for name in names:visit(name)
 return out

def outputs():
 out={}
 p=ROOT/'internal/adapters/mcpclient/schema.go';s=p.read_text()
 defs=closure(['MCPClientProfile','MCPClientParameters','MCPClientEvidence'],D)
 for name,value in [('schemaDefs',{'$defs':defs}),('schemaProfileBody',D['MCPClientProfile']),('schemaParametersBody',D['MCPClientParameters']),('schemaEvidenceBody',D['MCPClientEvidence'])]:s=re.sub(r'(const '+name+r' = `)[^`]*`',lambda m:m[1]+compact(value)+'`',s)
 out[p]=s
 p=ROOT/'internal/connections/builtin_tools.go';s=p.read_text()
 probe={'$ref':'#/$defs/MCPClientEvidence','$defs':closure(['MCPClientEvidence'],D)}
 s,count=re.subn(r'(schemaMCPProbeOut\s*=\s*`)[^`]*`',lambda m:m[1]+compact(probe)+'`',s)
 assert count==1
 out[p]=s
 p=ROOT/'internal/connections/schema_defs.go';s=p.read_text()
 s,count=re.subn(r'(const schemaDefs = `)[^`]*`',lambda m:m[1]+compact({'$defs':model.D})+'`',s)
 assert count==1
 out[p]=s
 p=ROOT/'internal/connections/schemas.go';s=p.read_text()
 for op in ['_connections.resolve','_connections.tool.resolve']:
  o=OPS[op];line='\t"'+op+'": {`'+compact(o['input_schema'])+'`, `'+compact(o['output_schema'])+'`},'
  pat=r'^\s*"'+re.escape(op)+r'":.*$'
  if re.search(pat,s,re.M):s=re.sub(pat,lambda _:line,s,flags=re.M)
  else:s=s.replace('var operationSchemaBodies = map[string]opSchemas{','var operationSchemaBodies = map[string]opSchemas{\n'+line)
 s=re.sub(r'(schemaValidationRecordIn = `)[^`]*`',lambda m:m[1]+compact(OPS['_connections.validation.record']['input_schema'])+'`',s)
 out[p]=s
 profile={'$ref':'#/$defs/MCPClientProfile','$defs':closure(['MCPClientProfile'],D)}
 out[ROOT/'internal/connections/mcp_profile_schema.go']='// Code generated by tools/specgen/sync_mcp_runtime.py; DO NOT EDIT.\npackage connections\n\nimport "encoding/json"\n\nfunc withDefsMCPProfile() json.RawMessage { return json.RawMessage(`'+compact(profile)+'`) }\n'
 p=ROOT/'internal/effects/schemas.go';s=p.read_text();s=re.sub(r'(const wireDefs = `)[^`]*`',lambda m:m[1]+compact({'$defs':model.D})+'`',s)
 o=OPS['_effects.callback.evidence'];line='\t"_effects.callback.evidence": {Input:`'+compact(o['input_schema'])+'`, Output:`'+compact(o['output_schema'])+'`},'
 if re.search(r'^\s*"_effects.callback.evidence":.*$',s,re.M):s=re.sub(r'^\s*"_effects.callback.evidence":.*$',lambda _:line,s,flags=re.M)
 else:s=re.sub(r'(var wireSchemas = map\[string\][^{]+\{)',lambda m:m[1]+'\n'+line,s,count=1)
 out[p]=s
 p=ROOT/'internal/registry/catalog.json'
 catalog=json.loads(p.read_text());catalog['defs']={'$defs':closure(re.findall(r'"\$ref":\s*"#\/\$defs\/([^"/]+)"', json.dumps([OPS[o['id']] for o in catalog['operations']])),model.D)}
 # Keep the catalog file format revision; its public surface is a projection.
 for operation in catalog['operations']:
  source=OPS[operation['id']]
  for target,source_key in [('input','input_schema'),('output','output_schema'),('completion','completion_schema'),('description','behavior'),('scope_required','scope_required')]:
   operation[target]=source.get(source_key)
 out[p]=compact(catalog)+'\n'
 out[ROOT/'internal/mcp/defs.json']=compact(catalog['defs'])+'\n'
 return out

def main():
 check=argparse.ArgumentParser();check.add_argument('--check',action='store_true');args=check.parse_args()
 drift=[]
 for p,s in outputs().items():
  # Format generated/mirrored Go through the standard formatter deterministically.
  import subprocess
  if p.suffix=='.go':s=subprocess.run(['gofmt'],input=s,text=True,capture_output=True,check=True).stdout
  if args.check:
   if not p.exists() or p.read_text()!=s:drift.append(str(p.relative_to(ROOT)))
  else:p.write_text(s)
 if drift:raise SystemExit('runtime MCP schema drift: '+', '.join(drift))
 print('MCP runtime schemas checked' if args.check else 'MCP runtime schemas synchronized')
if __name__=='__main__':main()
