// Generated by tools/designtokens. Do not edit.
import 'package:flutter/material.dart';

abstract final class ZColorLight {
  static const Color accent = Color(0xFF315F49);
  static const Color accentInk = Color(0xFFFFFFFF);
  static const Color amber = Color(0xFF886022);
  static const Color amberWash = Color(0x22B88C44);
  static const Color avatarBlueBackground = Color(0xFFDAE5ED);
  static const Color avatarBlueForeground = Color(0xFF416278);
  static const Color avatarLavenderBackground = Color(0xFFE3DDEC);
  static const Color avatarLavenderForeground = Color(0xFF635479);
  static const Color avatarMintBackground = Color(0xFFD2E4D7);
  static const Color avatarMintForeground = Color(0xFF254C36);
  static const Color avatarPeachBackground = Color(0xFFEADBCC);
  static const Color avatarPeachForeground = Color(0xFF70533B);
  static const Color canvas = Color(0xFFFAFBF8);
  static const Color card = Color(0xFFFFFFFF);
  static const Color composer = Color(0xFFFFFFFF);
  static const Color decisionLine = Color(0xFFC9B38F);
  static const Color error = Color(0xFF9B3B2C);
  static const Color hover = Color(0xFFE8ECE6);
  static const Color line = Color(0xFFD8DDD6);
  static const Color muted = Color(0xFF5D6A61);
  static const Color overlayScrim = Color(0x88000000);
  static const Color sidebar = Color(0xFFF0F2EE);
  static const Color subtle = Color(0xFF647168);
  static const Color text = Color(0xFF222B25);
  static const Color userBubble = Color(0xFFFFFFFF);
}

abstract final class ZColorDark {
  static const Color accent = Color(0xFFFCFCFC);
  static const Color accentInk = Color(0xFF111111);
  static const Color amber = Color(0xFFE4C391);
  static const Color amberWash = Color(0x20B88C44);
  static const Color avatarBlueBackground = Color(0xFF2C3840);
  static const Color avatarBlueForeground = Color(0xFFADCCDF);
  static const Color avatarLavenderBackground = Color(0xFF35323F);
  static const Color avatarLavenderForeground = Color(0xFFC7B9E3);
  static const Color avatarMintBackground = Color(0xFFB8D8C8);
  static const Color avatarMintForeground = Color(0xFF20352B);
  static const Color avatarPeachBackground = Color(0xFF42372E);
  static const Color avatarPeachForeground = Color(0xFFE0BA92);
  static const Color canvas = Color(0xFF070707);
  static const Color card = Color(0xFF262626);
  static const Color composer = Color(0xFF2F2F2F);
  static const Color decisionLine = Color(0xFF4A4334);
  static const Color error = Color(0xFFE8A598);
  static const Color hover = Color(0xFF323232);
  static const Color line = Color(0xFF232323);
  static const Color muted = Color(0xFFA0A0A0);
  static const Color overlayScrim = Color(0x88000000);
  static const Color sidebar = Color(0xFF111111);
  static const Color subtle = Color(0xFF929292);
  static const Color text = Color(0xFFE7E7E7);
  static const Color userBubble = Color(0xFF5A5A5A);
}

abstract final class ZSpacing {
  static const double lg = 16;
  static const double md = 12;
  static const double sm = 8;
  static const double xl = 24;
  static const double xs = 4;
  static const double xxl = 32;
}

abstract final class ZRadius {
  static const double card = 18;
  static const double control = 12;
  static const double dialog = 18;
}

abstract final class ZPanel {
  static const double composerMinHeight = 40;
  static const double gutter = 16;
  static const double width = 360;
}

abstract final class ZTypography {
  static const String family = 'system-ui';
  static const double bodySmall = 12;
  static const double bodyMedium = 14;
  static const double bodyLarge = 15;
  static const double titleMedium = 15;
  static const double titleLarge = 22;
  static const double headlineSmall = 24;
}
