package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const (
	pinJSON = `{"revision":1,"flutter_sdk":{"version":"3.32.1","framework_revision":"b25305a8832cfc6ba632a7f87ad455e319dccce8","dart_sdk":"3.8.1"}}`
	// pubspecLock is the sdks block as "flutter pub get" writes it.
	pubspecLock = "# Generated by pub\n# See https://dart.dev/tools/pub/glossary#lockfile\npackages:\n  async:\n    dependency: transitive\n    description:\n      name: async\n      sha256: \"d2872f9c19731c2e5f10444b14686eb7cc85c76274bd6c16e1816bff9a3bab63\"\n      url: \"https://pub.dev\"\n    source: hosted\n    version: \"2.13.0\"\nsdks:\n  dart: \">=3.8.1 <4.0.0\"\n  flutter: \">=3.29.0\"\n"
	machineJSON = `{"frameworkVersion":"3.32.1","channel":"stable","repositoryUrl":"https://github.com/flutter/flutter.git","frameworkRevision":"b25305a8832cfc6ba632a7f87ad455e319dccce8","engineRevision":"1425e5e9ec5eeb4f225c401d8db69b860e0fde9a","dartSdkVersion":"3.8.1","devToolsVersion":"2.45.1","flutterVersion":"3.32.1"}`
)

func TestReadFlutterPin(t *testing.T) {
	t.Parallel()
	pin, err := readFlutterPin([]byte(pinJSON))
	if err != nil || pin.Version != "3.32.1" || pin.DartSDK != "3.8.1" {
		t.Fatalf("readFlutterPin = %+v, %v", pin, err)
	}
	cases := map[string]string{
		"no pin":                `{"revision":1}`,
		"not json":              `{`,
		"floating version":      strings.Replace(pinJSON, `"3.32.1"`, `"stable"`, 1),
		"short revision":        strings.Replace(pinJSON, "b25305a8832cfc6ba632a7f87ad455e319dccce8", "b25305a", 1),
		"dart version is range": strings.Replace(pinJSON, `"dart_sdk":"3.8.1"`, `"dart_sdk":">=3.8.1"`, 1),
	}
	for name, src := range cases {
		if _, err := readFlutterPin([]byte(src)); faultCode(err) != codePrerequisiteMissing {
			t.Errorf("%s: error = %v, want %s", name, err, codePrerequisiteMissing)
		}
	}
}

func TestBindPin(t *testing.T) {
	t.Parallel()
	pin := flutterPin{Version: "3.32.1", FrameworkRevision: strings.Repeat("a", 40), DartSDK: "3.8.1"}
	if err := bindPin(pin, []byte(pubspecLock)); err != nil {
		t.Fatalf("matching pin: %v", err)
	}
	cases := []struct {
		name string
		pin  flutterPin
		lock string
		code string
	}{
		{"flutter below the floor", flutterPin{Version: "3.28.9", DartSDK: "3.8.1"}, pubspecLock, codeVerificationFailed},
		{"dart below the floor", flutterPin{Version: "3.32.1", DartSDK: "3.7.0"}, pubspecLock, codeVerificationFailed},
		{"dart at the ceiling", flutterPin{Version: "3.32.1", DartSDK: "4.0.0"}, pubspecLock, codeVerificationFailed},
		{"no sdks block", pin, "packages: {}\n", codePrerequisiteMissing},
		{"exotic constraint", pin, strings.Replace(pubspecLock, `">=3.29.0"`, `"^3.29.0"`, 1), codePrerequisiteMissing},
		{"unparseable lock", pin, "sdks:\n  - a\n", codePrerequisiteMissing},
	}
	for _, tc := range cases {
		if err := bindPin(tc.pin, []byte(tc.lock)); faultCode(err) != tc.code {
			t.Errorf("%s: error = %v, want %s", tc.name, err, tc.code)
		}
	}
}

// TestRepositoryPubspecLockParses proves the subset parser reads the real
// lock file, which the Flutter job depends on.
func TestRepositoryPubspecLockParses(t *testing.T) {
	t.Parallel()
	src, err := os.ReadFile(filepath.Join("..", "..", "..", "apps", "desktop", "pubspec.lock"))
	if err != nil {
		t.Skipf("apps/desktop/pubspec.lock is not present: %v", err)
	}
	root, err := parseYAML(src)
	if err != nil {
		t.Fatalf("parseYAML(pubspec.lock): %v", err)
	}
	if v, ok := root.path("sdks", "flutter").scalar(); !ok || !strings.HasPrefix(v, ">=") {
		t.Errorf("sdks.flutter = %q", v)
	}
}

func TestVerifyInstalledFlutter(t *testing.T) {
	t.Parallel()
	pin, _ := readFlutterPin([]byte(pinJSON))
	if err := verifyInstalledFlutter(pin, []byte(machineJSON)); err != nil {
		t.Fatalf("matching install: %v", err)
	}
	cases := map[string]string{
		"other version":  strings.Replace(machineJSON, `"frameworkVersion":"3.32.1"`, `"frameworkVersion":"3.32.2"`, 1),
		"other revision": strings.Replace(machineJSON, "b25305a8832cfc6ba632a7f87ad455e319dccce8", strings.Repeat("0", 40), 1),
		"other dart":     strings.Replace(machineJSON, `"dartSdkVersion":"3.8.1"`, `"dartSdkVersion":"3.8.2"`, 1),
	}
	for name, src := range cases {
		if err := verifyInstalledFlutter(pin, []byte(src)); faultCode(err) != codeVerificationFailed {
			t.Errorf("%s: error = %v", name, err)
		}
	}
	if err := verifyInstalledFlutter(pin, []byte("Flutter 3.32.1")); faultCode(err) != codePrerequisiteMissing {
		t.Errorf("non-JSON output: %v", err)
	}
}

func TestRunFlutterPinAndVerify(t *testing.T) {
	root := t.TempDir()
	write := func(rel, content string) {
		t.Helper()
		path := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	write("apps/desktop/pubspec.lock", pubspecLock)
	write("docs/implementation/dependencies.lock.json", `{"revision":1}`)
	write("flutter-version.json", machineJSON)
	outputs := filepath.Join(root, "outputs")
	evidence := filepath.Join(root, "evidence", "flutter-pin.json")
	var stdout, stderr bytes.Buffer
	args := []string{"flutterpin", "-root", root, "-out", evidence, "-output-file", outputs}
	if code := run(context.Background(), args, &stdout, &stderr); code != 5 {
		t.Fatalf("without a pin: exit %d, want 5; %s", code, stderr.String())
	}
	if _, err := os.Stat(outputs); err == nil {
		t.Fatal("outputs were written without a pin")
	}
	write("docs/implementation/dependencies.lock.json", pinJSON)
	if code := run(context.Background(), args, &stdout, &stderr); code != 0 {
		t.Fatalf("with a pin: exit %d; %s", code, stderr.String())
	}
	got, _ := os.ReadFile(outputs)
	if string(got) != "version=3.32.1\nrevision=b25305a8832cfc6ba632a7f87ad455e319dccce8\n" {
		t.Errorf("outputs = %q", got)
	}
	verify := []string{"flutterverify", "-root", root, "-version-file", filepath.Join(root, "flutter-version.json")}
	if code := run(context.Background(), verify, &stdout, &stderr); code != 0 {
		t.Fatalf("flutterverify: exit %d; %s", code, stderr.String())
	}
	write("flutter-version.json", strings.ReplaceAll(machineJSON, "3.32.1", "3.35.0"))
	if code := run(context.Background(), verify, &stdout, &stderr); code != 1 {
		t.Fatalf("flutterverify with another SDK: exit %d, want 1", code)
	}
}

func TestFlutterLayout(t *testing.T) {
	t.Parallel()
	app := t.TempDir()
	if _, err := flutterLayout(app); faultCode(err) != codePrerequisiteMissing {
		t.Fatalf("no pubspec.lock: %v", err)
	}
	if err := os.WriteFile(filepath.Join(app, "pubspec.lock"), []byte(pubspecLock), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Join(app, "macos"), 0o755); err != nil {
		t.Fatal(err)
	}
	outputs := filepath.Join(app, "outputs")
	var stdout, stderr bytes.Buffer
	args := []string{"flutterlayout", "-app", app, "-out", filepath.Join(app, "layout.json"), "-output-file", outputs}
	if code := run(context.Background(), args, &stdout, &stderr); code != 0 {
		t.Fatalf("flutterlayout: exit %d; %s", code, stderr.String())
	}
	got, _ := os.ReadFile(outputs)
	if string(got) != "integration_test=false\nlinux=false\nmacos=true\n" {
		t.Errorf("outputs = %q", got)
	}
}

func flutterEvents(lines ...string) string {
	return strings.Join(lines, "\n") + "\n"
}

func TestFlutterCollector(t *testing.T) {
	t.Parallel()
	start := `{"protocolVersion":"0.1.1","runnerVersion":null,"pid":1,"type":"start","time":0}`
	daemon := `[{"event":"test.startedProcess","params":{"vmServiceUri":null,"observatoryUri":null}}]`
	loading := `{"test":{"id":1,"name":"loading test/a_test.dart","suiteID":0,"groupIDs":[],"metadata":{"skip":false,"skipReason":null}},"type":"testStart","time":3}`
	loaded := `{"testID":1,"result":"success","skipped":false,"hidden":true,"type":"testDone","time":5}`
	passStart := `{"test":{"id":2,"name":"parses an envelope","suiteID":0,"groupIDs":[3]},"type":"testStart","time":6}`
	passDone := `{"testID":2,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":7}`
	failStart := `{"test":{"id":4,"name":"rejects an int64 overflow","suiteID":0,"groupIDs":[3]},"type":"testStart","time":8}`
	failPrint := `{"testID":4,"messageType":"print","message":"observed 2^63","type":"print","time":9}`
	failError := `{"testID":4,"error":"Expected: <true>","stackTrace":"package:test_api  expect\n","isFailure":true,"type":"error","time":10}`
	failDone := `{"testID":4,"result":"failure","skipped":false,"hidden":false,"type":"testDone","time":11}`
	skipStart := `{"test":{"id":5,"name":"mutual TLS exchange","suiteID":0,"groupIDs":[3],"metadata":{"skip":true,"skipReason":"openssl is absent"}},"type":"testStart","time":12}`
	skipDone := `{"testID":5,"result":"success","skipped":true,"hidden":false,"type":"testDone","time":13}`
	doneOK := `{"success":true,"type":"done","time":14}`
	doneFail := `{"success":false,"type":"done","time":14}`

	cases := []struct {
		name     string
		strict   bool
		exit     int
		stream   string
		passed   bool
		blocking string
	}{
		{"passing run", false, 0, flutterEvents(start, daemon, loading, loaded, passStart, passDone, doneOK), true, ""},
		{"skip tolerated outside release", false, 0, flutterEvents(start, loading, loaded, passStart, passDone, skipStart, skipDone, doneOK), true, ""},
		{"skip blocks a release gate", true, 0, flutterEvents(start, passStart, passDone, skipStart, skipDone, doneOK), false, "skipped"},
		{"failure", false, 1, flutterEvents(start, passStart, passDone, failStart, failPrint, failError, failDone, doneFail), false, "1 failed"},
		{"only loading entries", false, 0, flutterEvents(start, loading, loaded, doneOK), false, "no test ran"},
		{"runner did not finish", false, 0, flutterEvents(start, passStart, passDone), false, "did not report"},
		{"nonzero exit", false, 1, flutterEvents(start, passStart, passDone, doneOK), false, "exited 1"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			c := newFlutterCollector("flutter-test", nil, tc.strict)
			if err := c.consume(strings.NewReader(tc.stream)); err != nil {
				t.Fatal(err)
			}
			s := c.finish(tc.exit, false)
			if s.Passed != tc.passed {
				t.Fatalf("Passed = %v, want %v; blocking %v", s.Passed, tc.passed, s.Blocking)
			}
			if tc.blocking != "" && !strings.Contains(strings.Join(s.Blocking, "|"), tc.blocking) {
				t.Errorf("Blocking = %v, want %q", s.Blocking, tc.blocking)
			}
			if tc.name == "failure" {
				if len(s.Failed) != 1 || s.Failed[0].Test != "rejects an int64 overflow" || !strings.Contains(s.Failed[0].Output, "observed 2^63") || !strings.Contains(s.Failed[0].Output, "Expected: <true>") {
					t.Errorf("Failed = %+v", s.Failed)
				}
			}
			if tc.name == "passing run" && s.UnparsedLines != 1 {
				t.Errorf("the daemon event array should count as one unparsed line, got %d", s.UnparsedLines)
			}
		})
	}
}

func TestRunFlutterTestSubprocess(t *testing.T) {
	t.Setenv(helperEnv, "flutter-fail")
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	args := []string{"fluttertest", "-flutter", os.Args[0], "-prefix", "", "-name", "flutter-test", "-out-dir", dir, "-dir", dir, "--", "integration_test", "-d", "linux"}
	if code := run(context.Background(), args, &stdout, &stderr); code != 1 {
		t.Fatalf("exit %d, want 1; %s", code, stderr.String())
	}
	var s testSummary
	data, err := os.ReadFile(filepath.Join(dir, "flutter-test.summary.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, &s); err != nil {
		t.Fatal(err)
	}
	if s.Tests.Failed != 1 || s.Tests.Passed != 1 || s.ExitCode != 1 || len(s.Failed) != 1 {
		t.Fatalf("summary = %+v", s)
	}
	// The helper records its arguments in the failing test's output, which
	// proves the invocation shape "flutter test --machine <args>".
	if !strings.Contains(s.Failed[0].Output, "test --machine integration_test -d linux") {
		t.Errorf("invocation = %q", s.Failed[0].Output)
	}
	if got, _ := os.ReadFile(filepath.Join(dir, "flutter-test.stderr.txt")); string(got) != "some diagnostics\n" {
		t.Errorf("stderr evidence = %q", got)
	}
	t.Setenv(helperEnv, "flutter-pass")
	args = []string{"fluttertest", "-flutter", os.Args[0], "-prefix", os.Args[0] + " prefixed", "-strict", "-name", "flutter-test", "-out-dir", dir, "-dir", dir}
	if code := run(context.Background(), args, &stdout, &stderr); code != 0 {
		t.Fatalf("prefixed pass: exit %d; %s", code, stderr.String())
	}
}

func TestRunBounded(t *testing.T) {
	t.Setenv(helperEnv, "bounded")
	dir := t.TempDir()
	var stdout, stderr bytes.Buffer
	args := []string{"bounded", "-name", "flutter-analyze", "-out-dir", dir, "-dir", dir, "-max-log-bytes", "100", "--", os.Args[0], "analyze"}
	if code := run(context.Background(), args, &stdout, &stderr); code != 1 {
		t.Fatalf("exit %d, want 1; %s", code, stderr.String())
	}
	info, err := os.Stat(filepath.Join(dir, "flutter-analyze.log"))
	if err != nil || info.Size() != 100 {
		t.Fatalf("log = %v, %v; want exactly 100 bytes", info, err)
	}
	var rec struct {
		ExitCode     int      `json:"exit_code"`
		LogTruncated bool     `json:"log_truncated"`
		Dir          string   `json:"dir"`
		Command      []string `json:"command"`
	}
	data, err := os.ReadFile(filepath.Join(dir, "flutter-analyze.result.json"))
	if err != nil {
		t.Fatal(err)
	}
	if err := json.Unmarshal(data, &rec); err != nil {
		t.Fatal(err)
	}
	if rec.ExitCode != 4 || !rec.LogTruncated || rec.Dir != dir || len(rec.Command) != 2 {
		t.Errorf("result = %+v", rec)
	}
	if !strings.Contains(stdout.String(), "last line") {
		t.Errorf("console did not show the tail: %q", stdout.String())
	}
	args = []string{"bounded", "-name", "missing", "-out-dir", dir, "--", filepath.Join(dir, "no-such-tool")}
	if code := run(context.Background(), args, &stdout, &stderr); code != 5 {
		t.Errorf("missing tool: exit %d, want 5", code)
	}
}

func init() {
	// Additional helper scenarios for the test binary acting as flutter or
	// as an arbitrary bounded command; see TestMain.
	switch os.Getenv(helperEnv) {
	case "flutter-fail":
		fmt.Println(`{"protocolVersion":"0.1.1","type":"start","time":0}`)
		fmt.Println(`{"test":{"id":1,"name":"passes"},"type":"testStart","time":1}`)
		fmt.Println(`{"testID":1,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":2}`)
		fmt.Println(`{"test":{"id":2,"name":"records the invocation"},"type":"testStart","time":3}`)
		fmt.Printf("{\"testID\":2,\"messageType\":\"print\",\"message\":%q,\"type\":\"print\",\"time\":4}\n", strings.Join(os.Args[1:], " "))
		fmt.Println(`{"testID":2,"result":"failure","skipped":false,"hidden":false,"type":"testDone","time":5}`)
		fmt.Println(`{"success":false,"type":"done","time":6}`)
		fmt.Fprintln(os.Stderr, "some diagnostics")
		os.Exit(1)
	case "flutter-pass":
		if len(os.Args) < 2 || os.Args[1] != "prefixed" {
			fmt.Fprintf(os.Stderr, "prefix was not applied: %v\n", os.Args[1:])
			os.Exit(9)
		}
		fmt.Println(`{"test":{"id":1,"name":"passes"},"type":"testStart","time":1}`)
		fmt.Println(`{"testID":1,"result":"success","skipped":false,"hidden":false,"type":"testDone","time":2}`)
		fmt.Println(`{"success":true,"type":"done","time":3}`)
		os.Exit(0)
	case "bounded":
		for i := 0; i < 50; i++ {
			fmt.Println("analyzer output line", i)
		}
		fmt.Println("last line")
		os.Exit(4)
	}
}
