/* SPDX-License-Identifier: Apache-2.0 */
'use strict';
// In-memory interaction study. There is no controller, AI, provider, or network connection.
const paths={plus:'M12 5v14M5 12h14',search:'m21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',inbox:'M4 4h16l2 11v5H2v-5L4 4Zm-2 11h6l2 3h4l2-3h6',chevron:'m8 10 4 4 4-4',chat:'M21 11a9 9 0 0 1-9 9H4l-3 2 2-6a9 9 0 1 1 18-5Z',plug:'m8 3 1 5m6-5 1 5M6 8h12v4a6 6 0 0 1-12 0V8Zm6 10v4',settings:'m9 3 6 0 1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1 1-3ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',panel:'M3 4h18v16H3V4Zm12 0v16',arrow:'M12 20V4m-6 6 6-6 6 6',right:'M4 12h16m-6-6 6 6-6 6',close:'m6 6 12 12M6 18 18 6',check:'m5 12 4 4L19 6',clock:'M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-5v5l3 2',pin:'m8 3 8 0-1 6 3 4H6l3-4-1-6Zm4 10v8',people:'M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3m14-18a4 4 0 0 1 0 8m6 10v-3a4 4 0 0 0-4-4M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0',file:'M5 2h9l5 5v15H5V2Zm9 0v6h5M8 12h8m-8 4h6',shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6l9-4Zm-5 10 3 3 7-7',pause:'M8 5v14m8-14v14',play:'m7 4 13 8-13 8V4Z',offline:'m2 2 20 20M4 9a13 13 0 0 1 2-1m4-2a15 15 0 0 1 12 3M7 13a9 9 0 0 1 4-2m6 1 1 1m-8 4a3 3 0 0 1 4 0m-2 4h.01',menu:'M4 6h16M4 12h16M4 18h16',branch:'M6 3v12a4 4 0 0 0 4 4h8M6 8h12m-3-3 3 3-3 3m0 5 3 3-3 3',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3 3-7Z'};
const icon=name=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[name]||paths.chat}"/></svg>`;
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function hydrate(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{el.innerHTML=icon(el.dataset.icon);el.removeAttribute('data-icon');});}
const chats=[
 {id:'wren',parent:null,name:'Wren',initial:'W',color:'mint',org:'Personal',role:'Your chief',preview:'One thing needs your attention.',time:'Now'},
 {id:'marketing',parent:'wren',name:'Marketing chief',initial:'M',color:'peach',org:'Personal › Marketing',role:'Organization chief',preview:'Partnerships are taking shape.',time:'11:48'},
 {id:'research',parent:'marketing',name:'YouTube researcher',initial:'Y',color:'lavender',org:'Personal › Marketing',role:'Research worker',preview:'Three partnerships worth a look.',time:'10:32'},
 {id:'outreach',parent:'marketing',name:'Outreach',initial:'O',color:'peach',org:'Personal › Marketing',role:'Outreach worker',preview:'Your next introductions are ready.',time:'11:48'},
 {id:'engineering',parent:'wren',name:'Engineering chief',initial:'E',color:'blue',org:'Personal › Engineering',role:'Organization chief',preview:'The website review is underway.',time:'10:10'},
 {id:'quality',parent:'engineering',name:'Website reviewer',initial:'Q',color:'blue',org:'Personal › Engineering › Quality',role:'Quality chief',preview:'Checking the first-time experience.',time:'10:06'},
 {id:'ledger',parent:'wren',name:'Ledger',initial:'L',color:'blue',org:'Personal › Operations',role:'Operations chief',preview:'Reconciling this week’s expenses.',time:'09:41'}
];
const state={chat:'wren',panel:false,tab:'Work',filter:'All chats',review:'pending',offline:false,paused:false,memory:true,messages:{},drafts:{},connectionsTab:'Connections',light:false,notifications:true,created:[],setup:0,collapsed:new Set(['engineering'])};
const current=()=>chats.find(c=>c.id===state.chat)||chats[0];
function button(label,action,extra='',style=''){return `<button class="button ${style}" data-action="${action}" ${extra}>${label}</button>`;}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4200);}
function showModal(title,subtitle,body,footer=''){const d=$('#modal');$('#modal-content').innerHTML=`<div class="modal-head"><div><h2 id="modal-title">${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="icon-button" data-action="close" aria-label="Close dialog">${icon('close')}</button></div><div class="modal-body">${body}</div>${footer?`<div class="modal-footer">${footer}</div>`:''}`;if(!d.open)d.showModal();hydrate(d);}
function closeModal(){$('#modal').close();}
function renderChats(){
 const matches=c=>state.filter==='All chats'||c.org===state.filter||c.org.startsWith(state.filter+' › ');
 const containsMatch=c=>matches(c)||chats.some(child=>child.parent===c.id&&containsMatch(child));
 function node(c,depth){const children=chats.filter(child=>child.parent===c.id&&containsMatch(child));const expanded=!state.collapsed.has(c.id);const pending=(c.id==='outreach'||(c.id==='marketing'||c.id==='wren')&&!expanded)&&state.review==='pending';return `<li class="tree-node"><div class="tree-line ${state.chat===c.id?'selected':''}" style="--depth:${depth}">${children.length?`<button class="tree-toggle ${expanded?'expanded':''}" data-action="tree-toggle" data-id="${c.id}" aria-label="${expanded?'Collapse':'Expand'} ${esc(c.name)}" aria-expanded="${expanded}">${icon('chevron')}</button>`:'<span class="tree-spacer"></span>'}<button class="chat-row" data-action="chat" data-id="${c.id}" ${state.chat===c.id?'aria-current="page"':''}><span class="avatar ${c.color}">${esc(c.initial)}</span><span class="chat-copy"><span class="chat-name"><strong>${esc(c.name)}</strong>${c.id==='wren'?icon('pin'):pending?'<span class="dot" aria-label="Needs a decision"></span>':''}</span><span class="chat-preview">${esc(state.review!=='pending'&&['wren','outreach'].includes(c.id)?(c.id==='wren'?'You’re all caught up.':state.review==='approved'?'Approved · delivery not confirmed.':'Batch declined · nothing sent.'):c.preview)}</span><span class="chat-org">${esc(c.id==='wren'?'Personal · Your chief':c.role==='Organization chief'?c.org.split(' › ').at(-1)+' · Chief':c.org.replace('Personal › ',''))}</span></span></button></div>${children.length&&expanded?`<ul class="tree-children">${children.map(child=>node(child,depth+1)).join('')}</ul>`:''}</li>`;}
 $('#chats').innerHTML=`<ul class="chat-tree">${chats.filter(c=>!c.parent&&containsMatch(c)).map(c=>node(c,0)).join('')}</ul>`;$('#org-label').innerHTML=esc(state.filter)+' '+icon('chevron');$('#needs-count').textContent=state.review==='pending'?'1':'0';
}
function approvalCard(){const pending=state.review==='pending';return `<article class="decision-card"><div class="card-body"><div class="eyebrow">${icon(pending?'shield':'check')}${pending?'YOUR DECISION':state.review==='approved'?'APPROVED · DEMO':'DECLINED · DEMO'}</div><h3>${pending?'Ready to make a few introductions?':state.review==='approved'?'This batch has your approval.':'This batch will stay unsent.'}</h3><p>${pending?'Outreach prepared a personal note for 42 potential partners. This is above your usual limit of 25, so it’s waiting for your go-ahead.':state.review==='approved'?'Approval recorded in this demo. Delivery would be tracked separately; no messages have been sent.':'Outreach can prepare a smaller batch or revise the message. Your standing rules stay the same.'}</p><div class="card-meta"><span>${icon('people')}42 recipients</span><span>${icon('shield')}Up to $0.86 USD</span></div></div><div class="card-footer"><span>Outreach <span class="quiet">· Marketing</span></span>${button(pending?'Review & decide '+icon('right'):'View decision '+icon('right'),'review','','primary')}</div></article>`;}
function renderThread(){const c=current();$('#header-name').textContent=c.name;$('#header-avatar').textContent=c.initial;$('#header-avatar').className='avatar '+c.color;$('#breadcrumb').innerHTML=esc(c.org)+' <span>›</span> '+esc(c.role);$('#message').placeholder=`Ask ${c.name} to take something off your plate…`;$('#message').setAttribute('aria-label','Message '+c.name);$('#conversation').setAttribute('aria-label','Conversation with '+c.name);$('#composer-context').textContent=c.id==='wren'?'Wren will coordinate the right people.':`Talking directly to ${c.name}.`;
 let content='';
 if(c.id==='wren')content=`<div class="user-message">Morning, Wren. How are things looking?</div><div class="assistant-label"><span class="tiny-mark">z·</span> Wren <span>· 11:52 AM</span></div><div class="assistant-message"><p class="greeting">A good morning. A little less on your plate.</p><p>Your team has been moving things along. Here’s where we are:</p><ul class="summary-list"><li>${icon('check')}<div>Your inbox is sorted. <span>Three important messages are flagged.</span></div></li><li>${icon('check')}<div>The partnership shortlist is ready. <span>Research found three strong fits.</span></div></li><li><span class="spinning">${icon('clock')}</span><div>Weekly expenses are in progress. <span>Ledger is on it.</span></div></li></ul><p>${state.review==='pending'?'Just one thing needs you.':'You’re all caught up on decisions.'}</p></div>${approvalCard()}<div class="response-foot"><span>Up to date at 11:52 AM</span><button class="inline-link" data-action="activity">${icon('clock')} View activity</button></div>`;
 else if(c.id==='outreach')content=`<div class="user-message">Prepare introductions for this week’s partner list.</div><div class="assistant-label"><span class="tiny-mark">z·</span> Outreach · 11:48 AM</div><div class="assistant-message"><p class="greeting">Your next introductions are ready.</p><p>I’ve prepared a short note and checked the recipient list for duplicates. You can review the complete message and all recipients before anything is sent.</p></div>${approvalCard()}`;
 else if(c.id==='research')content=`<div class="user-message">Find a few partners for our September workshop.</div><div class="assistant-label"><span class="tiny-mark">z·</span> Research · 10:32 AM</div><div class="assistant-message"><p class="greeting">Three promising places to start.</p><p>I compared eight candidates against your audience, location, and workshop goals. These three look like the closest fit.</p></div><article class="decision-card"><div class="card-body"><div class="eyebrow">${icon('check')}RESULT READY · SAMPLE</div><h3>September partnership shortlist</h3><p>Three recommendations, supporting sources, and a suggested first step for each.</p><div class="card-meta"><span>${icon('file')}Research brief</span><span>${icon('check')}Checks passed</span></div></div><div class="card-footer"><span>Personal › Marketing</span>${button('Open brief '+icon('right'),'file','','primary')}</div></article><button class="inline-link" data-action="evidence">View acceptance checks ${icon('right')}</button>`;
 else if(c.id==='ledger')content=`<div class="user-message">Keep our expenses organized every Friday.</div><div class="assistant-label"><span class="tiny-mark">z·</span> Ledger · 09:41 AM</div><div class="assistant-message"><p class="greeting">One less thing for Friday.</p><p>I’m matching the receipts to this week’s transactions. I’ll flag anything that needs a second look and leave you a summary.</p></div><article class="decision-card"><div class="card-body"><div class="eyebrow">${icon('clock')}ONGOING RESPONSIBILITY</div><h3>Weekly reconciliation</h3><p>Every Friday at 9:00 AM · America/Los_Angeles<br>Read receipts, match transactions, and prepare a report. No payments or transfers.</p><span class="status">${state.paused?'Paused · demo':'In progress · 18 of 24 receipts matched'}</span></div><div class="card-footer"><span>You can pause this anytime.</span>${button(state.paused?'View paused work':'Manage responsibility','routines','','primary')}</div></article>`;
 else if(c.id==='marketing')content=`<div class="user-message">How is the workshop coming along?</div><div class="assistant-label"><span class="tiny-mark">z·</span>Marketing chief · 11:48 AM</div><div class="assistant-message"><p class="greeting">The right people are coming together.</p><p>YouTube researcher found three potential collaborators. Outreach has prepared the introductions, and is waiting for your decision before sending.</p><p>You can talk to either worker directly in the sidebar. I’ll keep the bigger picture moving.</p></div>${approvalCard()}`;
 else if(c.id==='engineering'||c.id==='quality')content=`<div class="assistant-label"><span class="tiny-mark">z·</span>${esc(c.name)} · 10:10 AM</div><div class="assistant-message"><p class="greeting">Making the first visit feel easy.</p><p>The website review is underway. The scope is to read and test the public experience, then prepare a report. Publishing changes will need a separate decision.</p></div><article class="mini-card"><div class="status">${icon('clock')}In progress · sample task</div><h3>Review the first-time website experience</h3><p>Check navigation, clarity, and the path to getting started.</p></article>`;
 else content=`<div class="assistant-label"><span class="tiny-mark">z·</span>${esc(c.name)}</div><div class="assistant-message"><p class="greeting">A little help, right where you need it.</p><p>This ${c.role==='Group conversation'?'group':'worker'} was created in the design demo. Start with what you’d like to accomplish.</p></div>`;
 const messages=(state.messages[c.id]||[]).map(m=>m.type==='user'?`<div class="user-message">${esc(m.text)}</div>${m.unsent?'<p class="unsent">Unsent draft · not delivered</p>':''}`:`<div class="assistant-label"><span class="tiny-mark">z·</span> ${esc(c.name)} · Demo response</div><p class="panel-note">${esc(m.text)}</p>`).join('');
 $('#thread').innerHTML=`<div class="date-label">Today, September 17</div>${content}${messages}`;
 $('#suggestions').innerHTML=(c.id==='wren'?[['Show me the shortlist','file'],['What’s everyone working on?','work']]:c.id==='ledger'?[['View ongoing work','routines']]:[['View files','files'],['View permissions','permissions']]).map(([label,action])=>`<button data-action="${action}">${label}</button>`).join('');
}
function render(){renderChats();renderThread();if(state.panel)renderPanel();$('#offline-banner').hidden=!state.offline;$('#online-label').innerHTML=state.offline?'Saved view':'<i></i>Available';$('#offline-toggle').textContent=state.offline?'Reconnect demo':'Try offline';$('#details-button').setAttribute('aria-expanded',String(state.panel));}
function selectChat(id){state.drafts[state.chat]=$('#message').value;state.chat=id;let c=current();while(c.parent){state.collapsed.delete(c.parent);c=chats.find(p=>p.id===c.parent);}$('#message').value=state.drafts[id]||'';render();closeModal();$('.sidebar').classList.remove('show');}
function openPanel(tab='Work'){state.panel=true;state.tab=tab;$('#details').hidden=false;renderPanel();$('#details-button').setAttribute('aria-expanded','true');}
function renderPanel(){const c=current();let content='';const mini=(title,desc,footer,status='')=>`<article class="mini-card">${status?`<div class="status">${status}</div>`:''}<h3>${title}</h3><p>${desc}</p>${footer}</article>`;
 if(state.tab==='Work')content=`<p class="panel-note">${c.id==='wren'?'A shared view of the work Wren coordinates.':`Work assigned to ${esc(c.name)}.`}</p>`+((c.id==='wren'||c.id==='marketing'||c.id==='outreach')?`<p class="section-label">Needs your decision</p>${mini('Partner introductions','42 recipients · Marketing',button('Review batch','review'),state.review==='pending'?'Waiting for you':state.review==='approved'?'Approved · delivery not confirmed':'Declined')}`:'')+((c.id==='wren'||c.id==='ledger')?`<p class="section-label">In progress</p>${mini('Weekly reconciliation','Ledger · Operations',button('View responsibility','routines'),state.paused?'Paused · demo':icon('clock')+' Matching receipts')}`:'')+((c.id==='wren'||c.id==='marketing'||c.id==='research')?`<p class="section-label">Completed</p>${mini('Partnership shortlist','Research · Marketing',button('Open result','file')+' '+button('Checks','evidence'),icon('check')+' Acceptance checks passed')}`:'');
 if(state.tab==='Routines')content=`<p class="panel-note">Ongoing responsibilities keep working without a new message each time.</p>`+((c.id==='wren'||c.id==='ledger')?mini('Weekly reconciliation','Every Friday · 9:00 AM<br>America/Los_Angeles',button(state.paused?'View pause details':'Pause responsibility','pause')+'<small style="margin-top:12px">Read receipts and prepare a report. Cannot move money.</small>',state.paused?'Paused · demo':icon('clock')+' Next run · tomorrow'):'<div class="empty">No ongoing responsibilities in this conversation.</div>');
 if(state.tab==='Files')content=`<p class="panel-note">Results stay here, even after the conversation moves on.</p>`+((c.id==='wren'||c.id==='marketing'||c.id==='research')?mini('Partnership shortlist','Research brief · Today, 10:32 AM<br>Shared with Marketing and Wren',button('Open brief','file'),icon('file')+' Verified result'):'<div class="empty">No completed files in this conversation.</div>');
 if(state.tab==='Memory')content=`<p class="panel-note">Useful context, with a clear source and sharing scope.</p>`+(state.memory?mini('Keep introductions short','“Use a friendly, direct tone. Keep the first note under 100 words.”','<small>Scope · Personal › Marketing<br>Source · Alex’s message, September 14<br>Updated · September 16 · Current<br>Wren can read through an explicit sharing rule.</small><div class="detail-separator"></div>'+button('Remove from recall','forget'),'Shared preference'):'<div class="empty">Preference removed from active recall in this demo. Historical records remain.</div>');
 if(state.tab==='Access')content=`<p class="panel-note">${esc(c.name)}’s permissions are specific. New responsibilities do not add permissions.</p>${mini('Can prepare drafts','Read assigned sources and prepare files.','<small>Within the current organization’s scope.</small>',icon('check')+' Allowed')}${mini('Asks before sending','This outreach batch exceeds the standing limit of 25 recipients.',button('Inspect exact request','review'),icon('shield')+' Decision required')}<div class="section-label">Spending · USD</div><div class="mini-card"><h3>$4.82 spent of $20 daily limit</h3><div class="progress-track"><span></span></div><small>$0.86 reserved · $14.32 available<br>No unknown costs in this sample.</small></div>`;
 if(['engineering','quality'].includes(c.id)&&state.tab==='Work')content=mini('Review the website','Check the first-time experience and prepare a report.','<small>Read-only scope · no publishing permission.</small>',icon('clock')+' In progress · sample');
 if(!['wren','marketing','outreach','research'].includes(c.id)&&state.tab==='Memory')content='<div class="empty">No shared preferences in this sample scope.</div>';
 if(!['wren','marketing','outreach'].includes(c.id)&&state.tab==='Access')content=mini('Read and prepare drafts','Access only to assigned sources. No sending or publishing.','<small>Additional capabilities require an exact configuration plan.</small>',icon('shield')+' Scoped access · sample');
 if(!content.trim())content='<div class="empty">No work yet. Start in the conversation.</div>';
 $('#details').innerHTML=`<div class="panel-header"><h2>${esc(c.name)}’s details</h2><button class="icon-button" data-action="panel-close" aria-label="Close details">${icon('close')}</button></div><div class="panel-tabs">${['Work','Routines','Files','Memory','Access'].map(t=>`<button class="${t===state.tab?'active':''}" data-action="tab" data-tab="${t}" aria-pressed="${t===state.tab}">${t}</button>`).join('')}</div><div class="panel-content">${state.offline?'<div class="notice">Saved view · may be out of date</div>':''}${content}</div>`;
}
function review(){let settled=state.review!=='pending';showModal(settled?'Your decision':'Review partner introductions',settled?'Sample decision record · no email was sent':'Outreach · Personal › Marketing',`${state.offline?'<div class="notice">Offline. Reconnect to check the current request before deciding.</div>':''}${settled?`<div class="notice">${state.review==='approved'?'Approved for this batch only. Delivery is not confirmed.':'Declined. This batch remains unsent.'}</div>`:'<div class="notice">This sends email to 42 people. Your usual limit is 25 per batch.</div>'}<dl class="review-facts"><div><dt>Action</dt><dd>Send the message below once</dd></div><div><dt>From</dt><dd>Alex &lt;alex@example.com&gt;</dd></div><div><dt>Recipients</dt><dd>42 people · Partner list, version 3</dd></div><div><dt>Maximum reserved cost</dt><dd>$0.86 USD</dd></div><div><dt>Approval applies to</dt><dd>This exact message and recipient list</dd></div><div><dt>Expires</dt><dd>Today at 6:48 PM · sample time</dd></div></dl><div class="mail-preview"><small>MESSAGE PREVIEW · IDENTICAL CONTENT FOR ALL 42 RECIPIENTS</small><strong>A workshop we could build together</strong><p>Hello,</p><p>We’re putting together a small workshop for independent teams this September. Your work caught our eye, and we’d love to explore hosting a session together.</p><p>Would you be open to a quick conversation next week?</p><p>Thanks,<br>Alex</p></div><details><summary>See all 42 recipients</summary><div class="recipient-list">${Array.from({length:42},(_,i)=>`Partner ${String(i+1).padStart(2,'0')} · partner${i+1}@example.com`).join('<br>')}</div></details><details><summary>Why this needs you · rules & evidence</summary><ul class="evidence-list"><li>Standing rule: ask before sending more than 25 messages per batch.</li><li>11:46 · Message and recipient list prepared; duplicates checked.</li><li>11:48 · $0.86 USD reserved. Current authority and limits must be rechecked before dispatch.</li><li>Review binds message version 1, recipient list version 3, and action version 1. Changes require a new decision.</li><li>Approving does not change the standing rule. The worker cannot approve on your behalf.</li></ul></details>`,settled?button('Done','close','','primary'):`<small>Only this batch. Your standing rules stay the same.</small>${button('Decline','decline',state.offline?'disabled':'')}${button('Approve 42 emails','approve',state.offline?'disabled':'','primary')}`);}
function needs(){showModal('Needs you',state.review==='pending'?'One decision across your workspace.':'You’re all caught up.',state.review==='pending'?`<button class="choice" data-action="review"><span class="avatar peach">O</span><span><strong>Partner introductions</strong><small>Outreach · Personal › Marketing<br>42 recipients · up to $0.86 USD</small></span>${icon('right')}</button>`:'<div class="empty">No pending decisions. Your team can keep moving.</div>');}
function file(){showModal('Partnership shortlist','Research · September 17 · Sample result',`<div class="status">${icon('check')}Acceptance checks passed · sample evidence</div><p class="panel-note">Three candidates for the September workshop, selected for audience fit and complementary expertise. Fictional organizations are used throughout this prototype.</p>${[['Cedar Studio','Independent creative teams','Start with a joint session on running a small studio.'],['Northline Collective','Community-led learning','Propose a hands-on workshop for first-time founders.'],['Fieldwork Club','Practical business education','Explore a co-hosted session on sustainable team habits.']].map(([n,a,t])=>`<div class="mini-card"><h3>${n}</h3><p>${a}</p><small>${t}</small></div>`).join('')}<details><summary>Sources & sharing</summary><p>Fixture sources: candidate profiles A, B, and C, revision 1. Shared with Marketing and Wren through an explicit reporting binding. No external sites were consulted by this prototype.</p></details>`,button('View checks','evidence')+button('Done','close','','primary'));}
function evidence(){showModal('Result checks','Partnership shortlist · fixture evidence',`<p class="panel-note">A worker’s message is separate from a verified result. These are illustrative checks, not executed product qualification.</p>${['Three candidates included','Every recommendation has a linked source','Workshop audience and format addressed'].map(t=>`<div class="setting-row"><span>${t}</span><span class="status">${icon('check')}Passed · sample</span></div>`).join('')}<details><summary>Verification record</summary><p>Fixture verifier: shortlist-check / version 1. Inputs: workshop brief v1, candidate profiles v1. Result: report v1. A real result must retain pinned verifier identity, inputs, observations, and independently established acceptance.</p></details>`);}
function settings(){showModal('Your workspace','Keep Zatiti comfortable, quiet, and within your limits.',`<div class="tabs"><button class="active">General</button><button data-action="usage">Usage & limits</button></div><div class="setting-row"><div>Appearance<p>Choose the look that feels right.</p></div><select id="appearance" aria-label="Appearance"><option value="dark" ${!state.light?'selected':''}>Dark</option><option value="light" ${state.light?'selected':''}>Light</option></select></div><div class="setting-row"><div>Decision notifications<p>Notify me when my team needs my input.<br>Routine coordination stays quiet.</p></div><button role="switch" aria-label="Decision notifications" aria-checked="${state.notifications}" class="toggle" data-action="notifications"></button></div><div class="setting-row"><div>When you close the app<p>Authorized work continues on your running controller. Pause a responsibility to stop new work from starting.</p></div></div><div class="setting-row"><div>Workspace<p>Alex Morgan · Personal<br>Local design demo · no account connected.</p></div></div>`);}
function connections(tab=state.connectionsTab){state.connectionsTab=tab;showModal('Connections & skills','Give your team the tools and know-how for the job.',`<div class="tabs">${['Connections','Skills'].map(t=>`<button data-action="connection-tab" data-tab="${t}" class="${tab===t?'active':''}">${t}</button>`).join('')}</div><p class="panel-note">${tab==='Connections'?'Each connection has a clear scope. Adding one does not automatically grant every worker access.':'Skills are reusable instructions. Tool access and spending permissions are granted separately.'}</p>${(tab==='Connections'?[['G','GitHub','Repository access · connection required'],['W','Web sources','Bounded public-page reads · sample binding'],['E','Email','Future adapter · concept only']]:[['R','Research brief','Compare sources and prepare a cited shortlist'],['Q','Quality review','Check a result against agreed requirements']]).map(([i,n,d])=>`<div class="connection-row"><span class="avatar">${i}</span><div><h3>${n}</h3><p>${d}</p></div>${button('Inspect','inspect-connection',`data-name="${n}"`)}</div>`).join('')}`);}
function newMenu(){showModal('Make room for a little help','Start with one worker. Build a team when you need one.',[['people','Worker','A specialist in an existing organization.'],['branch','Organization','A new area of work, with its own chief.'],['chat','Group chat','A shared conversation with existing workers.']].map(([i,n,d])=>`<button class="choice" data-action="create-form" data-kind="${n}">${icon(i)}<span><strong>${n}</strong><small>${d}</small></span>${icon('right')}</button>`).join(''));}
function createForm(kind){state.createKind=kind;showModal('New '+kind.toLowerCase(),kind==='Group chat'?'A conversation, with everyone’s existing permissions.':'Describe the help you need. Review before creating.',`<form id="create-form" class="form-stack"><label>Name<input id="create-name" required maxlength="48" placeholder="${kind==='Organization'?'Engineering':kind==='Worker'?'Workshop planner':'Workshop planning'}"></label>${kind==='Group chat'?'<label>Participants<select id="create-parent"><option>Wren and Research</option><option>Wren and Outreach</option></select><small>Group membership does not share private memories or grant tool access. Shared files still need disclosure checks.</small></label>':`<label>${kind==='Organization'?'Parent organization':'Home organization'}<select id="create-parent">${[...new Set(chats.filter(c=>c.role.includes('chief')).map(c=>c.org))].map(o=>`<option ${o===current().org?'selected':''}>${o}</option>`).join('')}</select></label><label>What should ${kind==='Worker'?'this worker':'this organization'} help with?<textarea id="create-purpose" required placeholder="Describe the outcome in your own words."></textarea></label><small>${kind==='Organization'?'Includes one designated chief. Inherits the parent’s permission and spending ceilings.':'Starts with minimum permissions. No new organization is created.'}</small>`}</form>`,`<button class="button primary" type="submit" form="create-form">Review ${kind==='Group chat'?'group':'plan'} ${icon('right')}</button>`);}
function createPreview(){const name=$('#create-name').value.trim();if(!name)return;state.pendingCreate={name,kind:state.createKind,parent:$('#create-parent').value,purpose:$('#create-purpose')?.value.trim()||'Shared conversation'};const p=state.pendingCreate;showModal('Review '+p.kind.toLowerCase(),'Proposed · awaiting your decision',`<div class="mini-card"><h3>${esc(p.name)}</h3><p>${esc(p.purpose)}</p><small>${p.kind==='Group chat'?'Participants':'Organization'} · ${esc(p.parent)}</small></div><p class="panel-note">${p.kind==='Organization'?'Creates the organization and its chief together. No additional tool permissions.':p.kind==='Worker'?'Creates one worker in the selected organization. Starts with minimum permissions.':'Creates a conversation only. Home organizations, memory access, and permissions stay unchanged.'}</p><div class="notice">Design preview only. No configuration is written to Zatiti.</div>`,button('Back','create-back')+button('Create in demo','create-apply',state.offline?'disabled':'','primary'));}
function createApply(){if(state.offline)return;const p=state.pendingCreate,id='demo-'+(chats.length+1);const parent=p.kind==='Group chat'?null:(chats.find(c=>c.org===p.parent&&(c.role.includes('chief')||c.id==='wren'))?.id||'wren');chats.push({id,parent,name:p.kind==='Organization'?p.name+' chief':p.name,initial:p.name[0].toUpperCase(),color:'blue',org:p.kind==='Organization'?p.parent+' › '+p.name:p.kind==='Group chat'?'Personal':p.parent,role:p.kind==='Group chat'?'Group conversation':p.kind==='Organization'?'Organization chief':'Worker',preview:'Created · demo',time:'Now'});state.filter='All chats';selectChat(id);toast('Created in demo. No live configuration changed.');}
function onboarding(step=0){state.setup=step;const steps=[['Meet Wren. Make a little room.','Your personal chief brings the right people together, keeps work moving, and asks when a decision needs you.',`<div class="success-mark">${icon('spark')}</div><h1>Start with what you want to get done.</h1><p class="panel-note">You don’t need to build an organization chart or learn a new workflow. Tell Wren what’s on your plate.</p><div class="notice">Authorized work continues when you close the desktop, as long as your controller is running.</div>`],['Connect your workspace','A guided setup takes care of the prerequisites.',`<div class="form-stack"><label>Workspace name<input value="Personal" aria-label="Workspace name"></label><label>Model connection<select aria-label="Model connection"><option>Configured provider · sample connection</option></select><small>Production setup must verify a qualified provider and use protected credential entry. This prototype never collects credentials.</small></label></div>`],['Set a comfortable limit','Wren will work within your spending and permission limits.',`<div class="form-stack"><label>Daily spending limit · USD<input id="setup-limit" type="number" min="1" max="1000" value="20"></label><p class="panel-note">Start with drafting and research. Sending, publishing, and expanded access follow the exact standing rules and decisions you review.</p></div><div class="notice">Sample setup only. No provider is connected and no paid work can run.</div>`]];const [title,sub,body]=steps[step];showModal(title,sub,body,`<small>Step ${step+1} of 3 · Setup preview</small>${step?button('Back','setup-back'):''}${button(step===2?'Meet Wren':'Continue','setup-next','','primary')}`);}
function search(){showModal('Find anything','Search workers, results, responsibilities, and decisions.',`<input class="search-input" id="search-input" placeholder="Try “Marketing” or “shortlist”…" aria-label="Search workspace"><div id="search-results"></div>`);searchResults('');$('#search-input').focus();}
function searchResults(query){const entries=[...chats.map(c=>({name:c.name,desc:c.org,action:'chat',id:c.id})),{name:'Partnership shortlist',desc:'Result · Personal › Marketing',action:'file'},{name:'Weekly reconciliation',desc:'Responsibility · Personal › Operations',action:'routines'},...(state.review==='pending'?[{name:'Partner introductions',desc:'Needs your decision · Personal › Marketing',action:'review'}]:[])];const filtered=entries.filter(e=>(e.name+' '+e.desc).toLowerCase().includes(query.toLowerCase()));$('#search-results').innerHTML=filtered.map(e=>`<button class="choice" data-action="${e.action}" ${e.id?`data-id="${e.id}"`:''}><span><strong>${esc(e.name)}</strong><small>${esc(e.desc)}</small></span>${icon('right')}</button>`).join('')||'<div class="empty">No matches. Try a worker or organization name.</div>';}
function setOffline(value){state.offline=value;render();toast(value?'Offline preview. Decisions are unavailable; drafts remain unsent.':'Reconnected in demo. Unsent drafts have not been delivered.');}
function submitMessage(event){event.preventDefault();const text=$('#message').value.trim();if(!text)return;const msgs=state.messages[state.chat]||(state.messages[state.chat]=[]);msgs.push({type:'user',text,unsent:state.offline});if(!state.offline)msgs.push({type:'assistant',text:'This prototype doesn’t run an AI. In the product, I’d clarify the outcome, scope, and limits, then show a durable task or a configuration preview here.'});$('#message').value='';state.drafts[state.chat]='';renderThread();$('#conversation').scrollTop=$('#conversation').scrollHeight;}
const actions={
 'close':closeModal,'chat':el=>selectChat(el.dataset.id),'new':newMenu,'review':review,'needs':needs,'file':file,'evidence':evidence,'search':search,'settings':settings,'connections':()=>connections(),'create-form':el=>createForm(el.dataset.kind),'create-back':()=>createForm(state.createKind),'create-apply':createApply,
 'sidebar':()=>$('.sidebar').classList.toggle('show'),
 'tree-toggle':el=>{const id=el.dataset.id;if(state.collapsed.has(id))state.collapsed.delete(id);else state.collapsed.add(id);renderChats();$('#chats').querySelector(`[data-action="tree-toggle"][data-id="${id}"]`)?.focus();},
 'panel':()=>{if(state.panel)actions['panel-close']();else openPanel();},'panel-close':()=>{state.panel=false;$('#details').hidden=true;$('#details-button').setAttribute('aria-expanded','false');$('#details-button').focus();},'tab':el=>{state.tab=el.dataset.tab;renderPanel();},
 'work':()=>{closeModal();openPanel('Work');},'routines':()=>{closeModal();openPanel('Routines');},'files':()=>{closeModal();openPanel('Files');},'permissions':()=>{closeModal();openPanel('Access');},
 'approve':()=>{if(state.offline||state.review!=='pending')return;state.review='approved';render();review();toast('Approved in demo. Delivery has not been confirmed.');},
 'decline':()=>{if(state.offline||state.review!=='pending')return;state.review='declined';render();review();toast('Declined in demo. No emails were sent.');},
 'org':()=>showModal('Your organizations','Choosing an organization includes its descendants.', ['All chats',...new Set(chats.map(c=>c.org))].map(n=>`<button class="choice" data-action="filter" data-filter="${esc(n)}">${icon('branch')}<span><strong>${esc(n)}</strong><small>${n==='All chats'?'Everything in your workspace':n==='Personal'?'Root organization · includes all child organizations':'Includes nested organizations'}</small></span>${icon('right')}</button>`).join('')),
 'filter':el=>{state.filter=el.dataset.filter;state.collapsed.clear();renderChats();closeModal();},
 'activity':()=>showModal('Activity','Meaningful updates · quiet coordination stays in the background.',`<div class="setting-row"><span>11:52 · Wren summarized progress</span></div><div class="setting-row"><span>11:48 · Outreach requested your decision</span></div><div class="setting-row"><span>10:32 · Research result passed sample checks</span></div><div class="setting-row"><span>09:41 · Ledger started reconciliation</span></div><details><summary>Internal coordination</summary><p>Routine reports do not mark chats unread, change chat order, or trigger notifications. This is synthetic activity for the design.</p></details>`),
 'pause':()=>showModal(state.paused?'Responsibility paused':'Pause weekly reconciliation?',state.paused?'Acknowledged · simulated controller state':'Only this responsibility is affected.',`<p>${state.paused?'No new reconciliation runs will start in this demo.':'Pausing prevents new work from starting for this responsibility once the controller acknowledges it.'}</p><p class="panel-note">Already transmitted actions cannot be undone by pausing. No unresolved external actions are present in this sample.</p>${state.offline?'<div class="notice">Offline. A pause cannot be acknowledged until you reconnect.</div>':''}`,button('Close','close')+(state.paused?'':button('Pause responsibility','pause-confirm',state.offline?'disabled':'','primary'))),
 'pause-confirm':()=>{if(state.offline)return;state.paused=true;closeModal();render();toast('Pause acknowledged · simulated controller.');},
 'forget':()=>showModal('Remove this from active recall?','Keep introductions short',`<p>Marketing and Wren will no longer recall this preference through this binding after removal is acknowledged.</p><p class="panel-note">This does not erase earlier messages, past run context, backups, or historical evidence. Promoted copies require tracked reconciliation.</p>`,button('Keep preference','close')+button('Remove from recall','forget-confirm',state.offline?'disabled':'','primary')),
 'forget-confirm':()=>{if(state.offline)return;state.memory=false;closeModal();renderPanel();toast('Removed from active recall in demo. Historical records remain.');},
 'usage':()=>showModal('Usage & limits','Personal workspace · sample amounts in USD',`<div class="setting-row"><span>Spent today</span><strong>$4.82</strong></div><div class="setting-row"><span>Reserved for pending work</span><strong>$0.86</strong></div><div class="setting-row"><span>Unknown costs</span><strong>$0.00</strong></div><div class="setting-row"><span>Available within daily limit</span><strong>$14.32</strong></div><div class="setting-row"><span>Daily limit</span><strong>$20.00</strong></div><p class="panel-note">Organization limits sit within their parent’s budget. Unknown costs must stay visible and reserved until reconciled.</p>`),
 'notifications':el=>{state.notifications=!state.notifications;el.setAttribute('aria-checked',String(state.notifications));},
 'connection-tab':el=>connections(el.dataset.tab),
 'inspect-connection':el=>{const name=el.dataset.name;showModal(esc(name),state.connectionsTab==='Skills'?'Skill preview':'Connection preview',`<p>${name==='Email'?'The email workflow is an illustrative future adapter, carried over from the visual brief. It is not a qualified v1 capability.':state.connectionsTab==='Skills'?'Versioned instructions guide the work. Installing a skill does not add permissions.':'Connections bind named capabilities to specific workers and organizations.'}</p><div class="mini-card"><h3>Scope</h3><p>Personal › Marketing</p><small>Access must be explicitly assigned. Secrets never enter a conversation.</small></div><p class="panel-note">Design preview only. No connection is made by this prototype.</p>`,button('Back to catalog','connections'));},
 'attach':()=>$('#file-input').click(),
 'offline':()=>setOffline(!state.offline),'reconnect':()=>setOffline(false),
 'theme':()=>{state.light=!state.light;document.body.classList.toggle('light',state.light);$('#theme-toggle').textContent=state.light?'Dark appearance':'Light appearance';},
 'onboarding':()=>onboarding(0),'setup-back':()=>onboarding(state.setup-1),'setup-next':()=>{if(state.setup<2)onboarding(state.setup+1);else{const input=$('#setup-limit');if(!input.reportValidity())return;selectChat('wren');$('#message').focus();toast('Setup preview complete. Sample workspace opened.');}},
 'reset':()=>location.reload()
};
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(el&&!el.disabled)actions[el.dataset.action]?.(el);});
document.addEventListener('submit',e=>{if(e.target.id==='create-form'){e.preventDefault();createPreview();}});
document.addEventListener('input',e=>{if(e.target.id==='search-input')searchResults(e.target.value);});
document.addEventListener('change',e=>{if(e.target.id==='appearance'){state.light=e.target.value!=='light';actions.theme();}});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search();}if(e.key==='Escape'&&!$('#modal').open&&state.panel)actions['panel-close']();});
$('#composer').addEventListener('submit',submitMessage);
$('#message').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#composer').requestSubmit();}});
$('#file-input').addEventListener('change',e=>{const f=e.target.files[0];if(f)toast(`Selected “${f.name}” locally. No file was uploaded or shared.`);e.target.value='';});
$('#modal').addEventListener('click',e=>{if(e.target===$('#modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
hydrate();render();
