package contract

import "encoding/json"

// Sealed local decision tool names (docs/implementation/contracts.md,
// "Local decision tool schemas (revision 3)"). These are execution-local
// proposals the context builder registers as non-provider tool definitions:
// never routed through a connections.Tool/adapter and never given a
// provider operation mapping. A final reply alone may complete a chat turn;
// it never implicitly fulfills a task's required outputs, which only
// report_outputs (bound through _tasks.evidence.record) can do.
const (
	LocalDecisionToolReply         = "reply"
	LocalDecisionToolClarify       = "clarify"
	LocalDecisionToolReportOutputs = "report_outputs"
	LocalDecisionToolCycleDecision = "cycle_decision"
)

// Revision 3 schema-derived primitives, copied verbatim from the frozen
// $defs of docs/implementation/operations.json (revision 3, generated by
// tools/specgen/model.py). Each is a fully self-contained JSON Schema
// document (draft 2020-12): any $ref it uses is resolved against its own
// embedded $defs, so ValidateSchema needs no external registry lookup —
// exactly the "self-contained document pruned to reachable $defs" shape
// registry.Lookup returns at runtime (contracts.md, "Registry lookup and
// schema normalization").
//
// Package owners (execution, tasks, messaging, effects, installation, ...)
// reuse these directly in their own tests, so every implementation is
// checked against the identical frozen schema text instead of a
// hand-copied approximation, and without importing each other's packages.
var (
	// ScopeSchema mirrors $defs/Scope: every referenced object is
	// revalidated against it; only the five declared dimensions are
	// accepted (additionalProperties: false), so a smuggled extra scope
	// dimension is rejected at the wire boundary before any authorization
	// logic runs.
	ScopeSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"installation_id": {"type": "string", "format": "uuid"},
			"organization_id": {"type": "string", "format": "uuid"},
			"project_id": {"type": "string", "format": "uuid"},
			"worker_id": {"type": "string", "format": "uuid"},
			"task_id": {"type": "string", "format": "uuid"}
		},
		"required": ["installation_id"]
	}`)

	// ArtifactRefSchema mirrors $defs/ArtifactRef, the wire shape of the Go
	// ArtifactRef type above.
	ArtifactRefSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"id": {"type": "string", "format": "uuid"},
			"digest": {"type": "string", "pattern": "^[0-9a-f]{64}$"}
		},
		"required": ["id", "digest"]
	}`)

	// RequirementSchema mirrors $defs/Requirement, the wire shape of the Go
	// Requirement type above.
	RequirementSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"code": {"type": "string", "maxLength": 8192},
			"message": {"type": "string", "maxLength": 8192},
			"resource_id": {"type": "string", "format": "uuid"},
			"challenge_id": {"type": "string", "format": "uuid"}
		},
		"required": ["code", "message"]
	}`)

	// FaultSchema mirrors $defs/Fault. Unchanged since revision 2: no
	// revision 3 bullet touches Fault, so this is also the exact schema a
	// revision-2 persisted Fault validates against.
	FaultSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"code": {"type": "string", "maxLength": 8192},
			"message": {"type": "string", "maxLength": 8192},
			"retryable": {"type": "boolean"},
			"details": {"type": "object", "description": "Inert JSON data bounded by the enclosing size limit; never executable authority."}
		},
		"required": ["code", "message", "retryable"]
	}`)

	// ResultSchema mirrors $defs/Result (self-contained with a nested
	// Fault). Unchanged since revision 2: no revision 3 bullet touches
	// Result, so this is also the exact schema a revision-2 persisted
	// Result validates against.
	ResultSchema = json.RawMessage(`{
		"$defs": {
			"Fault": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"code": {"type": "string", "maxLength": 8192},
					"message": {"type": "string", "maxLength": 8192},
					"retryable": {"type": "boolean"},
					"details": {"type": "object", "description": "Inert JSON data bounded by the enclosing size limit; never executable authority."}
				},
				"required": ["code", "message", "retryable"]
			}
		},
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"schema": {"const": "zatiti.result/v1"},
			"command_id": {"type": "string", "format": "uuid"},
			"status": {"type": "string", "enum": ["completed", "accepted", "failed"]},
			"data": {"anyOf": [
				{"type": "object", "description": "Inert JSON data bounded by the enclosing size limit; never executable authority."},
				{"type": "null"}
			]},
			"error": {"anyOf": [{"$ref": "#/$defs/Fault"}, {"type": "null"}]},
			"next_cursor": {"anyOf": [{"type": "string", "maxLength": 8192}, {"type": "null"}]}
		},
		"required": ["schema", "command_id", "status", "data", "error", "next_cursor"]
	}`)

	// ReplyProposalSchema mirrors $defs/ReplyProposal.
	ReplyProposalSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {"text": {"type": "string", "maxLength": 8192}},
		"required": ["text"]
	}`)

	// ClarifyProposalSchema mirrors $defs/ClarifyProposal.
	ClarifyProposalSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {"question": {"type": "string", "maxLength": 8192}},
		"required": ["question"]
	}`)

	// ReportOutputsProposalSchema mirrors $defs/ReportOutputsProposal
	// (self-contained with a nested ArtifactRef). Only report_outputs
	// (bound through _tasks.evidence.record) can fulfill a task's required
	// outputs; a reply alone never does.
	ReportOutputsProposalSchema = json.RawMessage(`{
		"$defs": {
			"ArtifactRef": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"id": {"type": "string", "format": "uuid"},
					"digest": {"type": "string", "pattern": "^[0-9a-f]{64}$"}
				},
				"required": ["id", "digest"]
			}
		},
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"bindings": {
				"type": "array",
				"maxItems": 4096,
				"items": {
					"type": "object",
					"additionalProperties": false,
					"properties": {
						"name": {"type": "string", "maxLength": 8192},
						"artifact": {"$ref": "#/$defs/ArtifactRef"}
					},
					"required": ["name", "artifact"]
				}
			}
		},
		"required": ["bindings"]
	}`)

	// CycleDecisionProposalSchema mirrors $defs/CycleDecisionProposal.
	CycleDecisionProposalSchema = json.RawMessage(`{
		"type": "object",
		"additionalProperties": false,
		"properties": {
			"decision": {"type": "string", "enum": ["continue", "wait", "escalate", "done"]},
			"reason": {"type": "string", "maxLength": 8192},
			"next_wake": {"type": "string", "format": "date-time"}
		},
		"required": ["decision", "reason"]
	}`)

	// LocalDecisionToolSchema mirrors $defs/LocalDecisionTool: a discriminated
	// oneOf over the four sealed local decision proposals, self-contained
	// with its own nested $defs (including ArtifactRef, reachable through
	// ReportOutputsProposal). Exactly one branch may match: an instance
	// smuggling fields from more than one proposal kind, or fields no
	// proposal kind declares (an "operation", a principal/grant/review
	// decision), matches zero or more-than-one branch and is rejected.
	LocalDecisionToolSchema = json.RawMessage(`{
		"$defs": {
			"ArtifactRef": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"id": {"type": "string", "format": "uuid"},
					"digest": {"type": "string", "pattern": "^[0-9a-f]{64}$"}
				},
				"required": ["id", "digest"]
			},
			"ReplyProposal": {
				"type": "object",
				"additionalProperties": false,
				"properties": {"text": {"type": "string", "maxLength": 8192}},
				"required": ["text"]
			},
			"ClarifyProposal": {
				"type": "object",
				"additionalProperties": false,
				"properties": {"question": {"type": "string", "maxLength": 8192}},
				"required": ["question"]
			},
			"ReportOutputsProposal": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"bindings": {
						"type": "array",
						"maxItems": 4096,
						"items": {
							"type": "object",
							"additionalProperties": false,
							"properties": {
								"name": {"type": "string", "maxLength": 8192},
								"artifact": {"$ref": "#/$defs/ArtifactRef"}
							},
							"required": ["name", "artifact"]
						}
					}
				},
				"required": ["bindings"]
			},
			"CycleDecisionProposal": {
				"type": "object",
				"additionalProperties": false,
				"properties": {
					"decision": {"type": "string", "enum": ["continue", "wait", "escalate", "done"]},
					"reason": {"type": "string", "maxLength": 8192},
					"next_wake": {"type": "string", "format": "date-time"}
				},
				"required": ["decision", "reason"]
			}
		},
		"oneOf": [
			{"$ref": "#/$defs/ReplyProposal", "description": "reply"},
			{"$ref": "#/$defs/ClarifyProposal", "description": "clarify"},
			{"$ref": "#/$defs/ReportOutputsProposal", "description": "report_outputs"},
			{"$ref": "#/$defs/CycleDecisionProposal", "description": "cycle_decision"}
		]
	}`)
)
